steps:
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: false
      post_qualify: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

columns: 120
newline: native
cabal: true
