name:                speff
version:             0.1.0.0
github:              "githubuser/speff"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/speff#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- transformers
- atomic-primops

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DerivingStrategies
- ExistentialQuantification
- GADTs
- LambdaCase
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- UnicodeSyntax
- KindSignatures
- DataKinds
- PolyKinds
- RoleAnnotations
- TypeFamilies
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- UndecidableInstances
- RankNTypes
- ConstraintKinds
- FunctionalDependencies
- EmptyCase

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-unticked-promoted-constructors
- -Wpartial-fields
- -Wunused-type-patterns
- -ddump-hi
- -ddump-simpl
- -ddump-to-file
- -dsuppress-all
- -dsuppress-uniques

library:
  source-dirs: src

benchmarks:
  speff-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-T
    dependencies:
    - speff
    - eveff
    - tasty-bench
